language: node_js
node_js:
  - 13

os:
  - linux

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - node --version
  - npm --version
  - npm test
  - ./node_modules/.bin/ts-node tests/fixtures/smoke-testing.ts

notifications:
  email:
    on_success: change
    on_failure: change
