version: '3.8'
services:
  friday:
    image: wechaty/friday:latest
    labels:
      - com.centurylinklabs.watchtower.enable=true
    init: true
    env_file: .env
    expose:
      - 80
    container_name: friday
    network_mode: bridge
    volumes:
      - .wechaty:/bot/.wechaty
    environment:
      - WEB_PORT=80
      - WECHATY_NAME=Friday
      - WECHATY_LOG=verbose
      - WECHATY_PUPPET=wechaty-puppet-hostie
      - VIRTUAL_HOST=friday.chatie.io,friday.bot5.club
      - LETSENCRYPT_HOST=friday.chatie.io,friday.bot5.club
    healthcheck:
      test: ["CMD", "true"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
volumes:
  .wechaty:
