version: '3.7'
services:
  friday:
    image: wechaty/friday:latest
    init: true
    env_file: .env
    expose:
      - 80
    container_name: friday
    volumes:
      - .wechaty:~/.wechaty
    environment:
      - WEB_PORT=80
      - WECHATY_NAME=Friday
      - WECHATY_LOG=verbose
      - WECHATY_PUPPET=wechaty-puppet-hostie
    healthcheck:
      test: ["CMD", "true"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
volumes:
  .wechaty:
