version: '3.7'
services:
  friday:
    image: friday:test
    command: test
    container_name: friday_test
    environment:
      WECHATY_PLUGIN_INTERCOM_TOKEN              : "$WECHATY_PLUGIN_INTERCOM_TOKEN"
      WECHATY_PLUGIN_INTERCOM_WEBHOOK_PROXY_URL  : "$WECHATY_PLUGIN_INTERCOM_WEBHOOK_PROXY_URL"
      WECHATY_PLUGIN_FRESHDESK_PORTAL_URL        : "$WECHATY_PLUGIN_FRESHDESK_PORTAL_URL"
      WECHATY_PLUGIN_FRESHDESK_API_KEY           : "$WECHATY_PLUGIN_FRESHDESK_API_KEY"
      WECHATY_PLUGIN_FRESHDESK_WEBHOOK_PROXY_URL : "$WECHATY_PLUGIN_FRESHDESK_WEBHOOK_PROXY_URL"
      WECHATY_PLUGIN_QNAMAKER_ENDPOINT_KEY       : "$WECHATY_PLUGIN_QNAMAKER_ENDPOINT_KEY"
      WECHATY_PLUGIN_QNAMAKER_KNOWLEDGE_BASE_ID  : "$WECHATY_PLUGIN_QNAMAKER_KNOWLEDGE_BASE_ID"
      WECHATY_PLUGIN_QNAMAKER_RESOURCE_NAME      : "$WECHATY_PLUGIN_QNAMAKER_RESOURCE_NAME"
